//script for index.html of Jeníkuv web

setInterval(function(){document.getElementById("header").style.top = ((((window.innerWidth - 240)/16)*9)/2)+"px"}, 50) //centers the header in the middle of the video based on viewport width
setInterval(function(){document.getElementById("rest").style.marginTop = ((((window.innerWidth - 240)/16)*9)-document.getElementById("header").offsetHeight)+"px"}, 50) //offsets the rest of the page to not intersect the video
setInterval(function(){document.getElementById("bgVid").loop = true}, 50) // prevents user from turning off loop on bgVid
setInterval(colorChange, 1000) // makes the ad color change in an interval

function genHex(){
hexArray = ["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"]; // array of all possible hex code vars
newColor = "#" + hexArray[~~(Math.random() * hexArray.length)] + hexArray[~~(Math.random() * hexArray.length)] + hexArray[~~(Math.random() * hexArray.length)] + hexArray[~~(Math.random() * hexArray.length)] + hexArray[~~(Math.random() * hexArray.length)] + hexArray[~~(Math.random() * hexArray.length)] + "40";
return(newColor)
}
//assembles a functional hexcode

function colorChange(){
var i = 0;
while (i < document.getElementsByClassName('sidebarContent').length) {
  document.getElementsByClassName('sidebarContent')[i].style.backgroundColor = genHex();
  i++;
  }
}
// loops through all elements with "sidebarContent" class and assigns a color generated by genHex()

function sendMessage() {
  var request = new XMLHttpRequest();
  request.open("POST", "https://discord.com/api/webhooks/1101577727791874108/sBBsHOyYbZMiALN0IQhSjpRLEFPbFGOKEKavSlVVLs4DTQQVjdUrvcc5_4h2uZbRZC5c");

  request.setRequestHeader('Content-type', 'application/json');

  var params = {
    content: document.getElementById("feedbackInput").value
  }

  request.send(JSON.stringify(params));
}
// sends feedback to discord
